// src/components/BookingForm.tsx
"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, CheckCircle2, MessageCircle, Music2, Send, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { whatsappHref } from "./WhatsappButton";

const municipalities = ["Nezahualcóyotl", "Chimalhuacán", "Los Reyes La Paz", "Ixtapaluca", "Chalco", "Valle de Chalco", "Texcoco", "Ecatepec"];
const eventTypes = ["Serenata", "Boda", "XV años", "Cumpleaños", "Bautizo", "Aniversario", "Evento empresarial", "Pedida de mano", "Graduación", "Otro"];
const schema = z.object({
  name: z.string().trim().min(2, "Escribe tu nombre (mínimo 2 caracteres)."),
  phone: z.string().trim().regex(/^[\d\s()+-]{10,18}$/, "Escribe un teléfono válido.").refine(value => value.replace(/\D/g, "").length === 10, "Incluye los 10 dígitos de tu teléfono."),
  date: z.string().min(1, "Selecciona la fecha del evento.").refine(value => value >= new Date().toLocaleDateString("en-CA"), "La fecha no puede estar en el pasado."),
  time: z.string().min(1, "Selecciona una hora aproximada."),
  municipality: z.string().min(1, "Selecciona tu municipio."),
  eventType: z.string().min(1, "Selecciona el tipo de evento."),
  address: z.string().trim().min(5, "Comparte una dirección o referencia (mínimo 5 caracteres)."),
  comments: z.string().trim().max(500, "Máximo 500 caracteres.").optional(),
});
type FormData = z.infer<typeof schema>;

export function BookingForm() {
  const [open, setOpen] = useState(false);
  const [whatsappLink, setWhatsappLink] = useState("");
  const dialogRef = useRef<HTMLDivElement>(null);
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormData>({ resolver: zodResolver(schema) });
  const fieldClass = "booking-input";
  useEffect(() => {
    if (!open) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const closeOnEscape = (event: KeyboardEvent) => {
      if (event.key === "Escape") setOpen(false);
    };
    window.addEventListener("keydown", closeOnEscape);
    dialogRef.current?.querySelector<HTMLInputElement>("input")?.focus();
    return () => {
      window.removeEventListener("keydown", closeOnEscape);
      document.body.style.overflow = previousOverflow;
    };
  }, [open]);
  const onSubmit = (data: FormData) => {
    const message = ["Hola, me interesa cotizar una presentación del Mariachi Mexicanísimo.", "", `Nombre: ${data.name}`, `Teléfono: ${data.phone}`, `Fecha: ${data.date}`, `Hora: ${data.time}`, `Municipio: ${data.municipality}`, `Tipo de evento: ${data.eventType}`, `Dirección: ${data.address}`, `Comentarios: ${data.comments || "Sin comentarios"}`, "", "¿Podrían confirmarme disponibilidad y brindarme una cotización?"] .join("\n");
    setWhatsappLink(whatsappHref(message));
  };
  return <>
    <button className="compact-action action-book" type="button" onClick={() => { setWhatsappLink(""); setOpen(true); }}><Music2 size={19} />Reservar y cotizar</button>
    {open && <div className="booking-overlay" onClick={event => { if (event.target === event.currentTarget) setOpen(false); }}>
      <div className="booking-dialog" role="dialog" aria-modal="true" aria-labelledby="booking-title" ref={dialogRef}>
        <button className="booking-close" type="button" aria-label="Cerrar formulario" onClick={() => setOpen(false)}><X size={20} /></button>
        <form className="booking-form" onSubmit={handleSubmit(onSubmit)} noValidate>
          <div className="form-heading"><div><span>COTIZACIÓN SIN COMPROMISO</span><h2 id="booking-title">Cuéntanos tu plan</h2></div><Send size={19}/></div>
          <div className="form-grid">
            <label>Tu nombre<input className={fieldClass} autoComplete="name" placeholder="Nombre y apellido" {...register("name")}/>{errors.name&&<small className="field-error">{errors.name.message}</small>}</label>
            <label>Teléfono<input className={fieldClass} type="tel" autoComplete="tel" inputMode="tel" placeholder="55 1234 5678" {...register("phone")}/>{errors.phone&&<small className="field-error">{errors.phone.message}</small>}</label>
            <label>Fecha del evento<input className={fieldClass} type="date" min={new Date().toLocaleDateString("en-CA")} {...register("date")}/>{errors.date&&<small className="field-error">{errors.date.message}</small>}</label>
            <label>Hora aproximada<input className={fieldClass} type="time" {...register("time")}/>{errors.time&&<small className="field-error">{errors.time.message}</small>}</label>
            <label>Municipio<select className={fieldClass} defaultValue="" {...register("municipality")}><option value="" disabled>Elige tu municipio</option>{municipalities.map(value=><option key={value}>{value}</option>)}</select>{errors.municipality&&<small className="field-error">{errors.municipality.message}</small>}</label>
            <label>Tipo de evento<select className={fieldClass} defaultValue="" {...register("eventType")}><option value="" disabled>¿Qué celebramos?</option>{eventTypes.map(value=><option key={value}>{value}</option>)}</select>{errors.eventType&&<small className="field-error">{errors.eventType.message}</small>}</label>
            <label className="form-wide">Dirección o punto de referencia<input className={fieldClass} autoComplete="street-address" placeholder="Calle, colonia y referencia" {...register("address")}/>{errors.address&&<small className="field-error">{errors.address.message}</small>}</label>
            <label className="form-wide">Detalles adicionales <span>(opcional)</span><textarea className={fieldClass} rows={2} maxLength={500} placeholder="Duración, canciones especiales…" {...register("comments")}/>{errors.comments&&<small className="field-error">{errors.comments.message}</small>}</label>
          </div>
          {whatsappLink
            ? <div className="form-success"><CheckCircle2 size={18}/><div><p>Listo. Abre WhatsApp para revisar y enviar tu solicitud.</p><a className="button button-red form-submit" href={whatsappLink} target="_blank" rel="noreferrer"><MessageCircle size={17}/> Continuar a WhatsApp <ArrowRight size={17}/></a></div></div>
            : <button className="button button-red form-submit" disabled={isSubmitting} type="submit">{isSubmitting?"Preparando…":"Preparar mensaje de WhatsApp"}<ArrowRight size={17}/></button>}
          <p className="form-privacy">Tus datos se incluirán en el mensaje de WhatsApp. La fecha queda pendiente de confirmación.</p>
        </form>
      </div>
    </div>}
  </>;
}

// src/app/shared/booking-form.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, EventEmitter, Output, ViewChild, inject } from '@angular/core';
import { AbstractControl, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { SITE_CONFIG } from '../core/site-config';
import { LeadService } from '../core/lead.service';

@Component({
  selector: 'mm-booking-form',
  standalone: true,
  imports: [ReactiveFormsModule],
  template: `
    <form #bookingForm class="booking-form" [formGroup]="form" (ngSubmit)="submit()" aria-labelledby="booking-title" novalidate>
      <header class="form-header">
        <div>
          <p class="eyebrow">COTIZACIÓN SIN COMPROMISO</p>
          <h2 id="booking-title">Cuéntanos de tu evento</h2>
          <p id="booking-description">Completa los datos para preparar tu mensaje de WhatsApp.</p>
        </div>
        <button class="close" type="button" aria-label="Cerrar formulario" (click)="close.emit()">×</button>
      </header>

      <div class="form-field">
        <label for="booking-name">Nombre</label>
        <input id="booking-name" formControlName="name" autocomplete="name" placeholder="Tu nombre" maxlength="80" required [attr.aria-invalid]="form.controls.name.touched && form.controls.name.invalid" [attr.aria-describedby]="form.controls.name.touched && form.controls.name.invalid ? 'booking-name-error' : null">
        @if (form.controls.name.touched && form.controls.name.hasError('required')) { <small class="field-error" id="booking-name-error" role="alert">Escribe tu nombre para poder contactarte.</small> }
        @else if (form.controls.name.touched && form.controls.name.hasError('minlength')) { <small class="field-error" id="booking-name-error" role="alert">Escribe al menos 2 caracteres.</small> }
        @else if (form.controls.name.touched && form.controls.name.hasError('pattern')) { <small class="field-error" id="booking-name-error" role="alert">El nombre no puede contener solo espacios.</small> }
      </div>

      <div class="form-field">
        <label for="booking-phone">Teléfono de contacto</label>
        <input id="booking-phone" type="tel" formControlName="phone" autocomplete="tel-national" inputmode="numeric" placeholder="5512345678" maxlength="10" pattern="[0-9]{10}" required [attr.aria-invalid]="form.controls.phone.touched && form.controls.phone.invalid" [attr.aria-describedby]="form.controls.phone.touched && form.controls.phone.invalid ? 'booking-phone-error' : null">
        @if (form.controls.phone.touched && form.controls.phone.invalid) { <small class="field-error" id="booking-phone-error" role="alert">Ingresa los 10 dígitos de tu teléfono, solo números.</small> }
      </div>

      <div class="form-field">
        <label for="booking-event">Tipo de evento</label>
        <select id="booking-event" formControlName="eventType" required [attr.aria-invalid]="form.controls.eventType.touched && form.controls.eventType.invalid" [attr.aria-describedby]="form.controls.eventType.touched && form.controls.eventType.invalid ? 'booking-event-error' : null">
          <option value="">Selecciona una opción</option>
          @for (eventType of SITE_CONFIG.eventTypes; track eventType) { <option [value]="eventType">{{ eventType }}</option> }
        </select>
        @if (form.controls.eventType.touched && form.controls.eventType.invalid) { <small class="field-error" id="booking-event-error" role="alert">Selecciona el tipo de evento.</small> }
      </div>

      <div class="form-field">
        <label for="booking-date">Fecha del evento</label>
        <input id="booking-date" type="date" formControlName="date" [min]="today" required [attr.aria-invalid]="form.controls.date.touched && form.controls.date.invalid" [attr.aria-describedby]="form.controls.date.touched && form.controls.date.invalid ? 'booking-date-error' : null">
        @if (form.controls.date.touched && form.controls.date.hasError('required')) { <small class="field-error" id="booking-date-error" role="alert">Selecciona la fecha del evento.</small> }
        @else if (form.controls.date.touched && form.controls.date.hasError('pastDate')) { <small class="field-error" id="booking-date-error" role="alert">La fecha debe ser hoy o posterior.</small> }
      </div>

      <div class="form-field">
        <label for="booking-municipality">Municipio</label>
        <select id="booking-municipality" formControlName="municipality" required [attr.aria-invalid]="form.controls.municipality.touched && form.controls.municipality.invalid" [attr.aria-describedby]="form.controls.municipality.touched && form.controls.municipality.invalid ? 'booking-municipality-error' : null">
          <option value="">Selecciona tu municipio</option>
          @for (municipality of SITE_CONFIG.municipalities; track municipality) { <option [value]="municipality">{{ municipality }}</option> }
        </select>
        @if (form.controls.municipality.touched && form.controls.municipality.invalid) { <small class="field-error" id="booking-municipality-error" role="alert">Selecciona el municipio del evento.</small> }
      </div>

      <div class="form-field">
        <label for="booking-address">Dirección del evento</label>
        <input id="booking-address" formControlName="address" autocomplete="street-address" placeholder="Calle, colonia y número" maxlength="180" required [attr.aria-invalid]="form.controls.address.touched && form.controls.address.invalid" [attr.aria-describedby]="form.controls.address.touched && form.controls.address.invalid ? 'booking-address-error' : null">
        @if (form.controls.address.touched && form.controls.address.invalid) { <small class="field-error" id="booking-address-error" role="alert">Comparte una dirección (mínimo 5 caracteres).</small> }
      </div>

      <div class="form-field wide">
        <label for="booking-references">Referencias adicionales <span>(opcional)</span></label>
        <textarea id="booking-references" formControlName="references" rows="2" maxlength="500" placeholder="Horario, canción especial o cómo llegar"></textarea>
      </div>

      <button class="button button-primary submit" type="submit">Solicitar cotización por WhatsApp <span aria-hidden="true">↗</span></button>
      <p class="form-note">WhatsApp se abrirá con tu solicitud para que la revises y la envíes. La fecha queda pendiente de confirmación.</p>
    </form>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BookingFormComponent {
  @Output() readonly close = new EventEmitter<void>();
  @Output() readonly submitted = new EventEmitter<void>();
  @ViewChild('bookingForm') private readonly formElement?: ElementRef<HTMLFormElement>;

  readonly SITE_CONFIG = SITE_CONFIG;
  readonly today = this.getLocalDate();
  private readonly fb = inject(FormBuilder);
  private readonly leads = inject(LeadService);
  readonly form = this.fb.nonNullable.group({
    name: ['', [Validators.required, Validators.minLength(2), Validators.maxLength(80), Validators.pattern(/\S/)]],
    phone: ['', [Validators.required, Validators.pattern(/^\d{10}$/)]],
    eventType: ['', Validators.required],
    date: ['', [Validators.required, Validators.pattern(/^\d{4}-\d{2}-\d{2}$/), (control: AbstractControl) => control.value && control.value < this.today ? { pastDate: true } : null]],
    municipality: ['', Validators.required],
    address: ['', [Validators.required, Validators.minLength(5), Validators.maxLength(180), Validators.pattern(/\S/)]],
    references: ['', Validators.maxLength(500)],
  });

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      requestAnimationFrame(() => this.formElement?.nativeElement.querySelector<HTMLElement>('[aria-invalid="true"]')?.focus());
      return;
    }

    window.open(this.leads.buildWhatsAppUrl(this.form.getRawValue()), '_blank', 'noopener,noreferrer');
    this.submitted.emit();
    this.close.emit();
  }

  private getLocalDate(): string {
    const now = new Date();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    return `${now.getFullYear()}-${month}-${day}`;
  }
}
